############################################################
#
# libcuttle Makefile
# 	Generated by amyznikov at Aug 26, 2016
#
############################################################

SHELL=/bin/bash

LIBNAME=cuttle
VERSION = 0.0.1
ARCH=native
#ARCH=arm-linux-androideabi

LIB=lib$(LIBNAME).a


all: lib

include $(ARCH).mk


installdirs = $(addprefix $(DESTDIR)/,$(prefix) $(incdir) $(libdir) $(pcdir))
$(installdirs):
	mkdir -p $@


CPPFLAGS += -Iinclude -Isrc

#########################################

SUBDIRS += $(addprefix src/,. cothread corpc dns ifaddrs hash nanopb pb ssl) 
SOURCES += $(foreach s,$(SUBDIRS),$(wildcard $(s)/*.c))

HEADERS += $(wildcard include/cuttle/*.h include/cuttle/*/*.h)
INTERNAL_HEADERS += $(foreach s,$(SUBDIRS),$(wildcard src/$(s)/*.h))



#########################################

MODULES  += $(addsuffix .o,$(basename $(SOURCES)))
$(MODULES): $(HEADERS) $(INTERNAL_HEADERS)

lib : $(LIB)($(MODULES))
clean : ; find -name '*.o' -delete 
distclean: clean ; $(RM) $(LIB)


install: $(LIB) $(installdirs)
	cp $(LIB) $(DESTDIR)/$(libdir)/
	cp -r include/* $(DESTDIR)/$(incdir)/
	echo -e "" \
		"prefix=$(prefix)\n" \
		"exec_prefix=$(prefix)\n" \
		"libdir=$(libdir)\n" \
		"includedir=$(incdir)\n" \
		"\n" \
		"Name: $(LIBNAME)\n" \
		"Description: $(LIBNAME) library\n" \
		"Version: $(VERSION)\n" \
		"Requires:\n" \
		"Requires.private:\n" \
		"Conflicts:\n" \
		"Libs: -L$(libdir) -l$(LIBNAME)\n" \
		"Libs.private:\n" \
		"Cflags: -I$(incdir)\n" \
		> $(DESTDIR)/$(pc)


uninstall:
	$(RM) $(DESTDIR)/$(libdir)/$(LIB)
	$(RM) $(DESTDIR)/$(pc)
	$(RM) $(addprefix $(DESTDIR)/$(prefix)/,$(HEADERS))
	
	

test:
	@echo "ARCH='$(ARCH)'"
	@echo "SUBDIRS='$(SUBDIRS)'"
	@echo "NDK_ROOT=${NDK_ROOT}"
	@echo "CC=$(CC)"
	@echo "CFLAGS=$(CFLAGS)"
	@echo "CPPFLAGS=$(CPPFLAGS)"
	@echo "LDFLAGS=$(LDFLAGS)"
	@echo "SOURCES=$(SOURCES)"
	@echo "HEADERS=$(HEADERS)"
	@echo "MODULES=$(MODULES)"
